<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 maze.gltf
Author: Yobibren (https://sketchfab.com/brendonburlew)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-maze-2bd7e0ffbaad44c08ef9281fd734289b
Title: Simple Maze
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const { gltf } = useGltf('/maze.gltf');
</script>

{#if $gltf}
	<T is={ref} {...$$restProps}>
		<T.Mesh
			geometry={$gltf.nodes.Plane__0.geometry}
			material={$gltf.materials['Scene_-_Root']}
			rotation={[-Math.PI / 2, 0, 0]}
			scale={[24.32, 250.2, 24.32]}
		/>

		<slot {ref} />
	</T>
{/if}
